export const mockPedidosCliente = [
  {
    id_pedido: 2,
    id_pedido_display: "#PED-002",
    titulo: "Taça Térmica 350ml - 200 Unid.",
    descricao: "Inox 304 + Silk Screen com Logo",
    image: "/product/musc-cup.png",
    etapa_pedido: "Produção",
    etapa_label: "Personalizando",
    concluido: false,
    responsavel: "Gustavo Pimentel",
    data_inicio: "12 MAI 2026",
    data_fim: null,
  },
  {
    id_pedido: 8,
    id_pedido_display: "#PED-008",
    titulo: "Copo Térmico Inox 320ml - 120 Unid.",
    descricao: "Inox 304 + Logo 360° em Silk Screen",
    image: "/product/musc-cup.png",
    etapa_pedido: "Finalizados",
    etapa_label: "Concluído",
    concluido: true,
    responsavel: "Gustavo Pimentel",
    data_inicio: "21 MAI 2026",
    data_fim: "25 MAI 2026",
  },
];
