export const mockHistoricoPedidos = [
  {
    id_pedido: 1,
    id_pedido_display: "#00254",
    titulo: "Cartões de Visita - Premium Soft Touch",
    descricao: "Cartões impressos em papel couché 300g com acabamento soft touch e verniz localizado. Ideais para profissionais que buscam transmitir sofisticação e qualidade premium em seu material de apresentação.",
    image: "/product/foto-card.png",
    status: "Concluído",
    quantidade: "500 Unid.",
    total: "R$ 450,00",
    data: "12 OUT, 2023",
  },
  {
    id_pedido: 2,
    id_pedido_display: "#00231",
    titulo: "Plotagem Técnica - Projeto Residencial",
    descricao: "Plotagem em alta resolução de plantas técnicas em folhas A0, com fidelidade de cores e traços precisos. Ideal para projetos arquitetônicos e de engenharia.",
    image: "/product/musc-cup.png",
    status: "Concluído",
    quantidade: "12 Folhas A0",
    total: "R$ 1.280,00",
    data: "05 SET, 2023",
  },
  {
    id_pedido: 3,
    id_pedido_display: "#00231",
    titulo: "Plotagem Técnica - Projeto Residencial",
    descricao: "Plotagem em alta resolução de plantas técnicas em folhas A0, com fidelidade de cores e traços precisos. Ideal para projetos arquitetônicos e de engenharia.",
    image: "/product/musc-cup.png",
    status: "Em Produção",
    quantidade: "12 Folhas A0",
    total: "R$ 1.280,00",
    data: "05 SET, 2023",
  },
];
