export const mockHistoricoPedidos = [
  {
    id_pedido: 9,
    id_pedido_display: "#PED-009",
    titulo: "Kit Ferramentas 25 Peças - Clientes VIP",
    descricao: "Kit com 25 peças em aço carbono com caixa plástica personalizada. Logo na tampa da caixa em silk screen branco. Ideal para brindes corporativos premium.",
    image: "/product/musc-cup.png",
    status: "Concluído",
    quantidade: "80 Unid.",
    total: "R$ 3.250,00",
    data: "26 MAI, 2026",
  },
  {
    id_pedido: 8,
    id_pedido_display: "#PED-008",
    titulo: "Copo Térmico Inox 320ml - Equipe Comercial",
    descricao: "Copo térmico em aço inox 304 com parede dupla. Logo 360° em silk screen branco sobre corpo preto. Mantém temperatura por horas.",
    image: "/product/musc-cup.png",
    status: "Concluído",
    quantidade: "120 Unid.",
    total: "R$ 5.400,00",
    data: "25 MAI, 2026",
  },
  {
    id_pedido: 4,
    id_pedido_display: "#PED-004",
    titulo: "Power Bank 5.000mAh + 10.000mAh - Feira",
    descricao: "Power banks com gravação a laser do logo na capa frontal. Design compacto com indicador LED de nível de bateria. Cor branca com gravação prata.",
    image: "/product/musc-cup.png",
    status: "Conferindo",
    quantidade: "100 Unid.",
    total: "R$ 4.350,00",
    data: "15 MAI, 2026",
  },
];
